// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztutkxirbrinlktdqsmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0dXRreGlyYnJpbmxrdGRxc213Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjI4OTYsImV4cCI6MjA2NTQ5ODg5Nn0.M52lI_46vsn0D-w-MbE-pHByxcOErgZ4AFqqUvoUWXo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);